steps:
- name: gcr.io/cloud-builders/gcloud
  args:
    - functions
    - deploy
    - function-test
    - --source=https://source.developers.google.com/projects/${var.project}/repos/github_joshua9519_test-function/moveable-aliases/master
    - --trigger-http

