steps:
- name: gcr.io/cloud-builders/gcloud
  args:
    - functions
    - deploy
    - function-test
    - --source=https://source.developers.google.com/projects/$PROJECT_ID/repos/github_joshua9519_test-function/moveable-aliases/master/paths/
    - --trigger-http
