steps:
- name: gcr.io/cloud-builders/gcloud
  args:
    - functions
    - deploy
    - function-test
    - --source=.
    - --trigger-http
    - --runtime=go111
    - --region=europe-west1
    - --entry-point=HelloGet
